name: tryagainnew
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_tts: ^3.0.0
  flutter:
    sdk: flutter
  csv: ^5.0.2  # Библиотека для работы с CSV
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/data.txt
    - assets/data2.txt
    - assets/data2.csv
    - assets/default_image.jpg



  uses-material-design: true
